# Generated by Django 5.1.7 on 2025-03-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'freelancer')},
        ),
    ]
